### PR TITLE
Permit breadcrumbs to wrap when text length is long

### LINKED ISSUE #1357: Fix breadcrumb overflow
Breadcrumb text is overflowing its container on smaller screens

Screen Shot 2022-12-05 at 11 10 17
Screen Shot 2022-12-05 at 11 11 32
Screen Shot 2022-12-05 at 11 11 24

### PR DESCRIPTION
**Pull request by thatbudakguy**
Fixes #1357

### CODE REVIEW

**Comment by thatbudakguy** [comment]
## long lv4 crumb
### large screen
Screen Shot 2022-12-05 at 11 22 48
### small screen
Screen Shot 2022-12-05 at 11 22 55
## short lv4 crumb
### large screen
Screen Shot 2022-12-05 at 11 23 01
### small screen
Screen Shot 2022-12-05 at 11 23 05
## many lv3 crumbs
### large screen
Screen Shot 2022-12-05 at 11 22 25
### small screen
Screen Shot 2022-12-05 at 11 22 33

**Review by jcoyne — CHANGES_REQUESTED** [review]
Gary previously made mockups like this that indicated the final breadcrumb should be on it's own line:


Can we have Gary approve this departure from those designs?

**Comment by cbeer** [comment]
Gary asked for the final breadcrumb not to appear on its own line in https://github.com/projectblacklight/arclight/issues/1325.

**Review by jcoyne — APPROVED** [review]
Thanks for the context @cbeer

**Pull request merged**
