### PR TITLE
Remove the link from the title of the current component in component …

### LINKED ISSUE #515: Unlink the currently selected component
- [ ] Remove the link applied to the title of the currently selected component in component detail view

On the component detail page we highlight the current component and show some collection context around it.

Screen Shot 2019-07-18 at 2 23 13 PM

It (probably) makes sense for the other component titles shown for context to be linked but the link for the current component simply refreshes the page/context area. This is potentially confusing for the user, who likely would expect to see a different display of some sort when clicking the link of the current component.

### PR DESCRIPTION
**Pull request by seanaery**
…detail view. Closes #515.

### CODE REVIEW

**Comment by seanaery** [comment]
I'm going to close out this PR and start over in hopes it'll help resolve the Travis CI build issue.

**Comment by mejackreed** [comment]
@seanaery Are you able to restart the travis build? We might need to adjust some permissions there also.

**Comment by seanaery** [comment]
@mejackreed I didn't see a restart button so I assume not. I tried a couple workarounds to try to kick it: 1) closing & reopening the PR; 2) adding an empty commit, though both approaches seem to have gotten stuck on there being a previous fail.

**Comment by mejackreed** [comment]
Gotcha.. we can pair up on this at somepoint

**Pull request closed without merging**
