### PR TITLE
Read traject config file from CONFIG_PATH

### PR DESCRIPTION
**Pull request by marlo-longley**

### CODE REVIEW

**Comment by jcoyne** [comment]
At this point does it still make sense to use this rake task?  Why not just call traject by itself?

**Comment by marlo-longley** [comment]
@thatbudakguy and I were wondering that initially too. But this seemed like a simple change and one others might benefit from too especially now that it's easier to add custom config files with that seam.

**Comment by jcoyne** [comment]
@marlo-longley I guess I don't see why you'd want to use this at all. It's more indirection (read slower) and poorer error handling.   I'm not sure what the benefit is.

**Comment by marlo-longley** [comment]
@jcoyne I guess I meant the minor benefit of others being able to set CONFIG_PATH and still use Arclight's rake tasks.

Are you saying you prefer to rewrite new indexing tasks for VT/NTA?

**Comment by cbeer** [comment]
I'd tend to agree with @jcoyne; passing mysterious environment variables isn't a great pattern for extensibility. I'm not seeing  so much going on here that calling traject directly or through an application-specific rake task creates much of a burden. 

Alternatively, maybe we could store a path as part of the `Arclight::Engine.config` and let downstream applications change that configuration?

**Pull request closed without merging**
