### PR TITLE
add flex-wrap to pagination

### LINKED ISSUE #687: Pagination nav not wrapping on mobile
The pagination nav at the bottom of the search results seems to need an explicit `flex-wrap: wrap;`. On mobile, the `<li>` elements don't wrap, and it means you have to scroll the page left to see the full nav.

nav 1 nav 2

### PR DESCRIPTION
**Pull request by labradford**
closes #687 
### Issue
Pagination does not wrap on mobile

### Resolution
Add flex-wrap: wrap to .pagination

### Demo
Before:
<a href="https://cl.ly/e57a95909107" target="_blank"></a>

After:
<a href="https://cl.ly/6709d3dafbf8" target="_blank"></a>

### CODE REVIEW

**Comment by mejackreed** [comment]
I think this was fixed upstream already https://github.com/projectblacklight/blacklight/commit/b70e01340a5e9886f3e64c55486c57c65445b4ca

Should we just hold out for a release?

**Comment by labradford** [comment]
Makes sense to me to hold out then. Should I close this?

**Comment by mejackreed** [comment]
Sure thing

**Comment by labradford** [comment]
Closing as this is a fix in upstream in BlackLight that we will get with the next release

**Pull request closed without merging**
