### PR TITLE
Allow for multiple extents

### PR DESCRIPTION
**Pull request by marlo-longley**
I would love someone to verify that I interpreted the intent written in this ticket correctly:
Closes https://github.com/projectblacklight/arclight/issues/989

I would also love feedback on whether we need to repeat this logic for both the `_tesim` and `ssm` fields.

Also, since there was no discussion on the ticket, I assume this is non-controversial and desired by the group.

### CODE REVIEW

**Comment by seanaery** [comment]
@marlo-longley This is great progress and it moves this issue closer to fixed. A few thoughts...

### Multiple extents
Here's what I'd expect the result to become, i.e., rather than a single-item array, the doc should have multiple extents and only the first should concatenate the values from within the same `<physdesc>`:
```
expect(result['extent_ssm']).to equal_array_ignoring_whitespace ['1.25 Linear Feet (1 volume)', '1 document case', '16 DVDRs']
```
We have a related issue to tackle in #997 where we should be showing a badge for each extent, i.e., multiple extents should be OK as long as we fix that other issue.

### Removing `and`
With multiple values the `and` is coming from the default `separator_options` but can be overridden like has been done for several other fields in the `catalog_controller.rb` template. I.e.,
```
separator_options: {
      words_connector: '<br/>',
      two_words_connector: '<br/>',
      last_word_connector: '<br/>'
    }
```

### Repeating for `extent_tesim`
In the traject config you can just copy the value that was captured for `extent_ssm` into `extent_tesim` without repeating the logic. I.e.,
```
to_field "extent_tesim" do |_record, accumulator, context|
  accumulator.concat context.output_hash["extent_ssm"] || []
end
``` 
### Needed on components and collections alike
Since `<extent>` can be present in the top-level collection and in individual components, we'll need this tweak to also be present in `ead2_component_config.rb`; See: https://github.com/projectblacklight/arclight/blob/main/lib/arclight/traject/ead2_component_config.rb#L158-L159

**Comment by seanaery** [comment]
I definitely welcome additional feedback from @mmmmcode , @gwiedeman and anyone else who can advise on the EAD nuances around extents in #989 :-)

**Comment by marlo-longley** [comment]
Awesome thanks so much @seanaery !

**Comment by marlo-longley** [comment]
HI @seanaery  -- I believe I addressed all your comments. I also added code to close https://github.com/projectblacklight/arclight/issues/997, so now this PR addresses 2 issues. I would love feedback but here is what it's looking like: 
Screenshot 2023-12-07 at 4 56 08 PM
Screenshot 2023-12-07 at 4 39 00 PM

The one question I had was about the failing test. I don't really understand this what this test is trying to achieve by using the `extent` field:
https://github.com/projectblacklight/arclight/blob/0d73b631a8be6f864de6df19aaaab091a73c88ae/spec/models/arclight/document_downloads_spec.rb#L13

I am happy to edit the test to make it pass, but I am getting the feeling this was potentially a workaround that we can get rid of altogether?

**Comment by mmmmcode** [comment]
@seanaery @marlo-longley One thing I wonder about is the parentheses in the container summary text (<extent altrender="carrier">)- are those something we want to supply if they aren't present? Or is that something that should be addressed with local customizations?

**Comment by marlo-longley** [comment]
@mmmmcode Thanks for taking a look! In these fixtures the words in parentheses are provided directly from the XML, as if a cataloger had entered it that way. So I wasn't thinking we should alter that. I want to make sure I'm understanding you, though!

**Comment by mmmmcode** [comment]
From my perspective, the () provided by the cataloger looks like style
baked into content (like using <emph> to bold series titles), which I'm
always a fan of eliminating. But that might just be me ;)

**Comment by marlo-longley** [comment]
Thanks for explaining @mmmmcode -- I could see this for sure but I'm thinking it is a change that is not directly related to allowing for multiple extents, or properly grouping extents, as the tickets lay out. If we want to change the formatting of text in extents, my take is thag we should open a new ticket and discuss there, rather than lump new functionality into this particular PR.

**Review by seanaery — APPROVED** [review]

**Pull request merged**
