### PR TITLE
Remove Gemfile.extra

### PR DESCRIPTION
**Pull request by jcoyne**
There is no need to provide this

### CODE REVIEW

**Comment by thatbudakguy** [comment]
based on slack conversation — was this also blocker for blacklight 8 compatibility? just figured we should note that somewhere

**Comment by jcoyne** [comment]
nope, this just reduces complexity

**Comment by cbeer** [comment]
Is this going to conflict with https://github.com/projectblacklight/arclight/pull/1046?

**Comment by jcoyne** [comment]
@cbeer yes, but I can resolve that by moving it to the Gemfile if necessary.

**Comment by cbeer** [comment]
We can try it. My memory is, it might get tricky pointing at all the right versions of things at the right time, but 🤷‍♂️

**Pull request merged**
